name: cb-nmfsubnet
dependencies:
- appnope=0.1.0=py27_0
- apptools=4.2.1=py27_0
- backports_abc=0.4=py27_0
- chaco=4.5.0=np19py27_0
- configobj=5.0.6=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.9=py27_0
- enable=4.4.1=np19py27_0
- envisage=4.4.0=py27_1
- freetype=2.5.5=0
- futures=3.0.3=py27_0
- h5py=2.5.0=np19py27_3
- hdf5=1.8.15.1=2
- ipykernel=4.3.1=py27_0
- ipyparallel=5.0.1=py27_0
- ipython=4.1.2=py27_0
- ipython_genutils=0.1.0=py27_0
- jbig=2.1=0
- jpeg=8d=1
- jupyter_client=4.2.2=py27_0
- jupyter_core=4.1.0=py27_0
- lcms=1.19=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- matplotlib=1.4.3=np19py27_3
- mayavi=4.4.0=np19py27_0
- mkl=11.3.1=0
- networkx=1.11=py27_0
- numpy=1.9.3=py27_1
- openssl=1.0.2g=0
- pandas=0.16.2=np19py27_0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pil=1.1.7=py27_2
- pillow=3.1.1=py27_0
- pip=8.1.1=py27_0
- pyface=4.4.0=py27_0
- pygments=2.1.1=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.5.0=py27_0
- python.app=1.2=py27_4
- pytz=2016.1=py27_0
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np19py27_0
- seaborn=0.7.0=py27_0
- setuptools=20.3=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- traits=4.4.0=py27_0
- traitsui=4.4.0=py27_0
- vtk=5.10.1=py27_0
- wheel=0.29.0=py27_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - bctpy==0.5.0
  - cvu==0.5.1
  - dyne==0.6.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - mne==0.11.0
  - mtspec==0.3.x
  - nibabel==2.0.2

